c_stdlib_version:  # [unix]
  - 2.28  # [linux]
  - 11.3  # [osx and x86_64]
# build_c_stdlib:
#   - sysroot  # [linux]
docker_image:
  - quay.io/condaforge/linux-anvil-x86_64:alma9  # [linux and not ppc64le]
