c_stdlib_version:              # [unix]
  - '2.28'                     # [linux and x86_64]
  - '10.12'                    # [osx and x86_64]
docker_image:
  - quay.io/condaforge/linux-anvil-alma-x86_64:8 # [linux and x86_64]
